### ISSUE TITLE
Text edit not working on tablets/ipad

### ISSUE THREAD

**Issue by umerrinayat** [GrapesJS/touch#2]
Hi I'm facing some issue related to edit text on tablets and iPad. I have installed this package which enable the touch support on grapesjs. Everything is working except text editing. I can select the text but keyboard not showing up. I try to check the Dom element during this testing. The Dom parameter "contenteditable" is not there.

**Comment by darylamonica** [comment]
Did you close this because you got it to work? While using a mobile device I cannot get the keyboard to display when trying to edit a text field. Even using the grapes touch plugin does not help. There is an example here:

http://jsfiddle.net/v9kecdpz/

**Comment by umerrinayat** [comment]
No. After no response from anyone on this issue. I just used the workaround. Which is not good, but there is no other solution. I'll share the code which I found somewhere on the internet. 
```const textType = editor.DomComponents.getType('text');
editor.DomComponents.addType('text', {
  model: textType.model,
  view: textType.view.extend({
    events: {
      dblclick: function () {
        this.onActive();
      },
      touchend: function () {
        this.onActive();
      }
    }
  })
});

**Comment by darylamonica** [comment]
Thank you for taking time to help. I will give that a shot.
